---
- name: Download Nexus
  unarchive:
    src: "{{ nexus_download_url }}"
    dest: /opt
    remote_src: yes
    creates: /opt/nexus/bin/nexus
- name: Rename to Nexus
  shell: "mv nexus-{{ nexus_version }} nexus"
  args:
    chdir: /opt
    creates: nexus
- name: Ensure group "somegroup" exists
  group:
    name: nexus
    state: present
- name: Add User
  user:
    name: nexus
    group: nexus
    append: yes
- name: Recursively change ownership of a directory
  file:
    path: /opt
    state: directory
    recurse: yes
    owner: nexus
    group: nexus
- name: Add Nexus as a user
  lineinfile:
    dest=/opt/nexus/bin/nexus.rc
    line=run_as_user="nexus"
    regexp=^#run_as_user=*
    state=present
- name: Configure Nexus
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
  notify: 'Restart Nexus'
- name: Create a symbolic link
  file:
    src: /opt/nexus/bin/nexus
    dest: /etc/init.d/nexus
    owner: nexus
    group: nexus
    state: link
    mode: '755'
- name: Start Nexus
  command: ./nexus start
  args:
    chdir: /opt/nexus/bin
- name: Register service with chkconfig system
  service: name=nexus enabled=yes