---
# tasks file for apache
#
- name: Include Vars
  include_vars: "{{ ansible_os_family }}.yml"
#
- name: Import task install_packages_rhel.yml
  import_tasks: install_packages_rhel.yml
  tags: install_pkg_rhel
#
- name: Import task configure_vhost.yml
  import_tasks: configure_vhost.yml
  tags: vhost  
# 
- name: Disable SELinux
  selinux:
    state: disabled