galaxy_info:
  author: Team
  description: Generate self-signed SSL certificate
  company: Team
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []

dependencies: []